### ISSUE TITLE
fragment bug.

### ISSUE THREAD

**Issue by clm2733227** [zhouzhuo810/ZzLettersSideBar#1]

**Comment by zhouzhuo810** [comment]
你是不是没有调用 sideBar.setLetterTouchListener()？

**Comment by clm2733227** [comment]
有啊
`zzLetterSideBar.setLetterTouchListener(zzRecyclerView, mAdapter, null, new OnLetterTouchListener() {
            @Override
            public void onLetterTouch(String letter, int position) {
                int rvPos = mAdapter.getPositionForSection(letter.charAt(0));
                ((LinearLayoutManager) zzRecyclerView.getLayoutManager()).scrollToPositionWithOffset(rvPos, 0);
            }

            @Override
            public void onActionUp() {

            }
        });`

**Comment by clm2733227** [comment]
`zzLetterSideBar.setLetterTouchListener(zzRecyclerView, mAdapter, null, new OnLetterTouchListener() {
            @Override
            public void onLetterTouch(String letter, int position) {
                int rvPos = mAdapter.getPositionForSection(letter.charAt(0));
                ((LinearLayoutManager) zzRecyclerView.getLayoutManager()).scrollToPositionWithOffset(rvPos, 0);
            }

            @Override
            public void onActionUp() {

            }
        });`

**Comment by clm2733227** [comment]
有啊 要自己加入layoutmanager才可以正常跳转。你自己写个fragment试试。
zzLetterSideBar.setLetterTouchListener(zzRecyclerView, mAdapter, null, new OnLetterTouchListener() {
            @Override
            public void onLetterTouch(String letter, int position) {
                int rvPos = mAdapter.getPositionForSection(letter.charAt(0));
          ((LinearLayoutManager)zzRecyclerView.getLayoutManager()).scrollToPositionWithOffset(rvPos, 0);
            }

            @Override
            public void onActionUp() {

            }
        });

**Comment by zhouzhuo810** [comment]
我试了fragment，没问题啊，这个监听是给你做别的用的，但是也不能不写，传参数用的不需要你自己调用滚动操作的。
